################################################################################
# SIMDadd
#       formal coverage enable -code bcefst ;
#       formal verify -timeout 5m -sanity_waveforms -cov_mode signoff; 
################################################################################
run:compile formal 

###### Define Variables ########################################################
VLIB = D:\\questaformal\\QFT_2021.1\\QFT\\V2021.1\\win64\\share\\modeltech\\win64\\vlib
VMAP = D:\\questaformal\\QFT_2021.1\\QFT\\V2021.1\\win64\\share\\modeltech\\win64\\vmap
VLOG = D:\\questaformal\\QFT_2021.1\\QFT\\V2021.1\\win64\\share\\modeltech\\win64\\vlog

# Default module if not specified
MODULE ?= i2c_master_top

###### Compile Design ##########################################################
compile:
	$(VLIB) work
	$(VMAP) work work
	$(VLOG) -sv ./src/rtl/${MODULE}.sv 

###### Run Formal Analysis #####################################################
formal:
	qverify -c -od ./tmp/${MODULE}/Output_Results -do "\
		formal compile -d ${MODULE} -include_code_cov; \
		formal verify -timeout 1m -auto_constraint_off -sanity_waveforms -cov_mode observability; \
		formal coverage enable -code bcefst ;\
		formal generate coverage -detail_all;\
		exit"

###### Debug Results ###########################################################
debug: 
	qverify Output_Results/formal_verify.db &

###### Clean Data ##############################################################
clean:
	qverify_clean
	\rm -rf work modelsim.ini *.wlf *.log replay* transcript *.db
	\rm -rf .\tmp\${MODULE}\Output_Results *.do 

################################################################################
# Regressions 
################################################################################
REGRESS_FILE_LIST = \
	Output_Results/formal_property.rpt \
	Output_Results/formal_verify.rpt

regression: clean compile formal
	@rm -f regress_file_list
	@echo "# This file was generated by make" > regress_file_list
	@/bin/ls -1 $(REGRESS_FILE_LIST) >> regress_file_list
	@chmod -w regress_file_list